#!/bin/bash
# Deployment Script - Push to GitHub and Deploy to Live Servers

echo "🚀 Fieldnote Deployment Script"
echo "================================"
echo ""

# Step 1: GitHub Setup
echo "📌 STEP 1: GitHub Repository Setup"
echo "===================================="
echo ""
echo "We've already initialized Git and committed your code."
echo "Now you need to:"
echo ""
echo "1️⃣  Create a GitHub repository:"
echo "   - Go to: https://github.com/new"
echo "   - Enter repo name: fieldnote-app"
echo "   - DON'T initialize with README (you already have files)"
echo "   - Click Create Repository"
echo ""
echo "2️⃣  Copy the commands shown on GitHub and run them:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/fieldnote-app.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3️⃣  After pushing, continue with deployment steps below..."
echo ""
echo "================================"
echo ""

# Step 2: Backend Deployment
echo "🔧 STEP 2: Deploy Backend to Render.com"
echo "======================================"
echo ""
echo "1️⃣  Go to: https://render.com"
echo "2️⃣  Sign in with GitHub"
echo "3️⃣  Click 'New +' → 'Web Service'"
echo "4️⃣  Select your 'fieldnote-app' repository"
echo ""
echo "Configuration:"
echo "  • Name: fieldnote-backend"
echo "  • Environment: Node"
echo "  • Build Command: npm install"
echo "  • Start Command: npm start"
echo "  • Root Directory: backend"
echo "  • Region: (choose closest to you)"
echo "  • Plan: Free"
echo ""
echo "Environment Variables to Add:"
echo "  NODE_ENV=production"
echo "  PORT=5000"
echo "  MONGO_URI=mongodb+srv://username:password@cluster.mongodb.net/fieldnote?retryWrites=true&w=majority"
echo "  RAZORPAY_KEY_ID=your_razorpay_key_id"
echo "  RAZORPAY_KEY_SECRET=your_razorpay_key_secret"
echo "  FRONTEND_URLS=https://your-frontend-url.vercel.app (add after frontend deployment)"
echo ""
echo "5️⃣  Click Deploy"
echo "6️⃣  Wait 5-10 minutes"
echo "7️⃣  Copy your backend URL (something like: https://fieldnote-backend.onrender.com)"
echo ""
echo "Note: You'll need MongoDB Atlas & Razorpay credentials first!"
echo "  - MongoDB: https://www.mongodb.com/cloud/atlas"
echo "  - Razorpay: https://razorpay.com"
echo ""
echo "======================================="
echo ""

# Step 3: Frontend Deployment
echo "🎨 STEP 3: Deploy Frontend to Vercel"
echo "===================================="
echo ""
echo "1️⃣  Go to: https://vercel.com"
echo "2️⃣  Sign in with GitHub"
echo "3️⃣  Click 'Add New' → 'Project'"
echo "4️⃣  Select your 'fieldnote-app' repository"
echo ""
echo "Configuration:"
echo "  • Framework: Vite"
echo "  • Root Directory: frontend"
echo "  • Build Command: npm run build"
echo "  • Output Directory: dist"
echo ""
echo "Environment Variable:"
echo "  VITE_API_URL=https://your-backend-url.onrender.com/api"
echo "  (Replace with your actual Render backend URL from Step 2)"
echo ""
echo "5️⃣  Click Deploy"
echo "6️⃣  Wait 2-5 minutes"
echo "7️⃣  Copy your frontend URL (something like: https://fieldnote-frontend.vercel.app)"
echo ""
echo "======================================"
echo ""

# Step 4: Final Backend Update
echo "🔄 STEP 4: Update Backend CORS"
echo "=============================="
echo ""
echo "1️⃣  Go back to Render.com dashboard"
echo "2️⃣  Click on your backend service"
echo "3️⃣  Go to 'Environment' tab"
echo "4️⃣  Update FRONTEND_URLS to:"
echo "   https://your-frontend-url.vercel.app,https://www.your-domain.com"
echo ""
echo "5️⃣  Click 'Save Changes'"
echo "6️⃣  Click 'Manual Deploy'"
echo ""
echo "=============================="
echo ""

# Final Status
echo "✅ DEPLOYMENT COMPLETE!"
echo "========================"
echo ""
echo "Your app is now LIVE! 🎉"
echo ""
echo "Frontend URL: https://your-frontend-url.vercel.app"
echo "Backend URL: https://your-backend-url.onrender.com"
echo ""
echo "Test it by:"
echo "  1. Open your frontend URL"
echo "  2. Try the payment flow"
echo "  3. Check browser console (F12) for any errors"
echo ""
echo "Having issues? Check:"
echo "  - Backend logs in Render dashboard"
echo "  - Frontend logs in Vercel dashboard"
echo "  - Browser console (F12)"
echo ""
